### ISSUE TITLE
Configurable timeout for currentJournalEventsByTag

### ISSUE THREAD

**Issue by skisel** [dnvriend/akka-persistence-jdbc#123]
We've migrated to the latest version of akka-persistence-jdbc (3.0.0), but currently our dev database is slow for some reason and I see that we're getting a lot of timeouts for the call currentJournalEventsByTag method.

I see in the code it is hardcoded to 100ms:

`import akka.pattern.ask
    implicit val askTimeout = Timeout(100.millis)
    Source.fromFuture(orderingActor.ask(GetMaxOrderingId).mapTo[MaxOrderingId])`

Should be probably at least be able to customize it.

**Comment by WellingR** [comment]
I agree that it should be possible to customize it.

However it does surprise me that timeouts occur here, since the orderingActor should always respond immediately with the last known value.

**Comment by skisel** [comment]
In case of application startup and database is very slow (shared oracle instance), it could get time out here.

**Comment by skisel** [comment]
Thank you very much!

**Comment by WellingR** [comment]
FYI
@skisel I have recently discovered #155 it seems to be that an ask timeout of the journal sequence actor can be caused by very large gaps in the database, typically this can occur when the first event does not have 1 (or 0) as the first id, but a very large value.

I hope to fix this in the next version of akka-persistence-jdbc. For now, increasing the timeout is the only workaround.

Since you state that your issue occurs on a dev database (the same happened in my case) maybe you should consider resetting the sequence value for the journal table when you truncate the database (if you do this at all).

**Comment by skisel** [comment]
Thanks @WellingR, I will have a look. I think you're right, it happens really with high value of seqNr.
