### ISSUE TITLE
delaySource created with inverted arguments

### ISSUE THREAD

**Issue by renatocaval** [dnvriend/akka-persistence-jdbc#125]
At [this line](https://github.com/dnvriend/akka-persistence-jdbc/blob/master/src/main/scala/akka/persistence/jdbc/query/scaladsl/JdbcReadJournal.scala#L84) we see the definition of `delaySource`:

```
Source.tick(readJournalConfig.refreshInterval, 0.seconds, 0).take(1)
```
This should be:
```
Source.tick(0.seconds, readJournalConfig.refreshInterval, 0).take(1)
```

**Comment by WellingR** [comment]
Actually the method signature reads

```
def tick[T](initialDelay: FiniteDuration, interval: FiniteDuration, tick: T): Source[T, Cancellable]
```

Since we use `take(1)` we only use the initial delay, and ignore the interval. However I have been confused about this too a while ago. Feel free to submit a PR where both the intialDelay and the interval use the same value `readJournalConfig.refreshInterval`

**Comment by rcavalcanti** [comment]
Hmm, true about `take(1)`. I'm wondering if that's correct. 

When we `take`, the upstream stops after emitting the based number (1). I don't see now how the stream doesn't stop, because the Slick stream further in the chain is finite. When the table is fully read it stops. 

I was expecting the tick to trigger a new query and keep the stream flowing. I need to have another look on this.

I've prepared a PR but the tests are failing because the the timing changed. Now that you mentioned it, I need to review the whole thing. Thanks for the heads-up.

To be continued...

**Comment by WellingR** [comment]
eventsByTag uses `Source.unfoldAsync` which has the following signature
`def unfoldAsync[S, E](s: S)(f: S ⇒ Future[Option[(S, E)]]): Source[E, NotUsed]`

In our case f returns a future which comes from a stream starting with the `delaySource`. An effect of this is that the time to complete this future is always at least `refreshInterval`.

This method is not perfect, one disadvantage is that the current code is not as fast as possible since the delay is used for every batch that this retrieved. For example if `readJournalConfig.maxBufferSize` is very small (say 10 for this example) and `readJournalConfig.refreshInterval` is relatively large (say 1 second for example) then an eventsByTag query will only return 10 events per second.

This shows that there is some room for improvement here. (for example by omitting the delay whenever the number of retrieved events is equal to `maxBufferSize`)
