### ISSUE TITLE
SQL Error using sharding region and timeout

### ISSUE THREAD

**Issue by giampaolotrapasso** [dnvriend/akka-persistence-jdbc#18]
I have a bunch of actors under a sharding region. They do persistence and snapshots. When an actor reaches an inactivity timeout it gets terminated. However when sharding region awakes it, I get an error like this:

    [error] 3157 [example-akka.actor.default-dispatcher-18] ERROR scalikejdbc.StatementExecutor$$anon$1 - SQL execution failed (Reason: Duplicate entry 'SnapshotActor-4-11' for key 'PRIMARY'):
    [error] 
    [error]    INSERT INTO snapshot (persistence_id, sequence_nr, created, snapshot) VALUES ('SnapshotActor-4', 11, 1430927955209, 'BAAAAAEAAACs7QAFc3IAL3NhbXBsZS5wZXJzaXN0ZW5jZS5TbmFwc2hvdEV4YW1wbGUkRXhhbXBsZVN0YXRlhG/BFNOFpT4CAAFM... (492)')
[error] 

Since it's quite difficult to reproduce, I prepared an artificial example at [https://github.com/giampaolotrapasso/akka-sharding-jdbc-persistence-problem](https://github.com/giampaolotrapasso/akka-sharding-jdbc-persistence-problem). The example it's not something I'd actually code, but it's useful to reproduce the problem I see in my project (that I cannot share).

**Comment by dnvriend** [comment]
I have forked your project; thanks by the way, this is super! It seems that the id could not be determined correctly. I have changed changed the project a bit so I can test it quickly. I have created a pull request for you to merge, test and study. For inspiration, maybe you can take a look at this id extractor: [click] (https://github.com/dnvriend/spray-ba-sharding/blob/master/src/main/scala/com/example/UserAndView.scala#L22).

**Comment by giampaolotrapasso** [comment]
Sorry for bugging you again, but I do not understand very well :)
I merged your PR and surely is written better than mine and it's more understandable, thanks. I will make mine something you used. However I need to understand this thing about persistence.

In your PR you have

    val idExtractor: ShardRegion.IdExtractor = {
      case (cmd: String, id: String) => ((id.hashCode % 10).toString, cmd)
    }

And it all works fine. However for sake of experimenting, I changed it to 
    
    val idExtractor: ShardRegion.IdExtractor = {
        case (cmd: String, id: String) => ((cmd.hashCode % 10).toString, cmd)
    }

Of course I'm messing up things a bit, since the *second* parameter of message is the one that identifies the actor under sharding. Anycase `cmd.hashCode % 10` is a 0-9 number like `id.hashCode % 10`, so even if I'm shuffling messages is should be a valid _idExtractor_. Using _"print"_ and _"snap"_ now I'm sending messages only to two (or one) actors, yes, but this should be an applicative error not relevant for persistence layer. Probably there's a flaw in my reasoning and you can help me to understand better.

**Comment by dnvriend** [comment]
#### Akka Cluster
Please read the [Akka Cluster Sharding Documentation](http://doc.akka.io/docs/akka/2.3.10/contrib/cluster-sharding.html#An_Example_in_Scala) that has an example how to create a `ShardRegion.IdExtractor ` and `ShardRegion.ShardResolver`. When I started out leaning Akka Cluster, trying out the samples and creating some of my own, I maybe have read the documentation every day for a week to understand how it works and every day I learned something new about it. This is especially true for the [How it works](http://doc.akka.io/docs/akka/2.3.10/contrib/cluster-sharding.html#How_it_works) part. I invite you to do the same :smile:. Its amazing how good the documentation is, and how much you can learn from it. Actually I have the same effect now as I had with Akka Cluster, I'm learning Akka-Streams, very cool stuff indead!

#### Akka Persistence Snapshotting
In akka-persistence-jdbc the primary key of the snapshot is  `(persistence-id +snapshot-version)`. The behavior of akka-persistence is as follows: 

_Only when an event has been persisted, the snapshot version number will be bumped._

Imagine, manually changing the state of the actor by _bypassing_ the `persist` call and thus not saving the event in the journal. This would effectively leave the journal table empty as you may expect. Instead explicitly changing only the state of the actor and then creating a `snapshot` every time therefor relying only on snapshotting, what would happen? Well, something unexpected. 

The version number of the snapshot entry changes - will be bumped - _only_ when a new journal entry has been written. So when bypassing the `persist` call, and only calling `snap`, this is the behavior we got. A shard entry, one that did not persist any entries, at all, because the id-resolution was a bit garbled, got a `snap` command multiple times, and did not write any `i.toString` commands (at all) earlier and thus tried to write only snapshots with the same primary key and that failed.

Actually, Akka clustering does the same, it writes snapshots explicitly multiple times with the same persistence-id and version. I got this behavior some time ago and created a poor-mans upsert query that fails but will recover by updating the snapshot. Please see the [akka-persistence-jdbc snapshot/Statements trait](https://github.com/dnvriend/akka-persistence-jdbc/blob/master/src/main/scala/akka/persistence/jdbc/snapshot/Statements.scala#L57). 

The akka-persistence snapshotting behavior is , as far as I know undocumented and not part of the akka-persistence-testkit created by Martin Krasser. There is a unit test for this behavior in akka-persistence-jdbc. 

I hope it is now a bit clearer why you got errors all over the log. The snapshot entry will first fail (INSERT) but will be recovered (UPDATE) so the snapshot contains the latest changes made to it. 

Your code had the combination, a shard entry that only did snapshots plus the poor-man's upsert with errors in the log that must be interpreted as, 'the INSERT failed, but the UPDATE did not fail', so all is well.

**Comment by giampaolotrapasso** [comment]
Thanks a lot for your explanation. Now it's more clear what's going behind the scenes! Thank you so much.
