### ISSUE TITLE
Access to JdbcAsyncWriteJournal

### ISSUE THREAD

**Issue by zmarois** [dnvriend/akka-persistence-jdbc#188]
I see that the [ReadJournal is exposed](https://github.com/dnvriend/akka-persistence-jdbc#how-to-get-the-readjournal-using-java), but how would I access the write journal?

I'd assume it needs to be accessible for @ktoso's recent feature in https://github.com/dnvriend/akka-persistence-jdbc/pull/183 to allow for updates. Is it currently accessible, and I just don't see how I would do so without creating a class in package `akka.persistence` so I can use the internal method `akka.persistence.Persistence.journalFor()`, or is that portion of the feature not figured out yet?

I definitely understand why this wouldn't be exposed: Although the class isn't private, its effectively an internal API; I shouldn't be able to raw-insert into the DB without utilizing the PersistentActor interface. I want to do so to support a DB migration. I already have PersistentActor data in a different data store, and I want to explore the performance of my system if it were using Postgres. To do so, I want to push all my existing data into Postgres, and if I use the JdbcAsyncWriteJournal to do so, I'll have confidence that it is in the correct format for the JdbcReadJournal to read.

**Comment by ktoso** [comment]
It's not a feature that should be used across the board really so it is intentionally not super exposed.
Yes, reaching into the journalFor is the strategy.

**Comment by WellingR** [comment]
You state that you want to do a db migration, are you migrating from one jdbc database to another? Or are you migrating from a different akka-persistence journal plugin?

In the first case you can see if the source database supports dumping the contents of the journal table in a format which the target database supports. If this is not the case then maybe you can use slick to query the `JournalRow`s in the source database and insert these in the target database.

In case of different akka-persistence the following might be options:

- Query the data, and see if some of the existing library code can be used to convert the data to a `PersistentRepr`, the `ByteArrayJournalSerializer` can serialize this to `JournalRow` which can be inserted using slick.
- Perhaps you can combine the `currentPersistenceIds` query with the  `currentEventsByPersistenceId` query,  so that you can send the events to a persistent actor again which stores the events using akka-persistence-jdbc

Note that the global event ordering (which determines the order for the events by tag query) is generated using a database sequence, so the order of inserting in the database determines the global event ordering. If you care about this then you should ensure that events are inserted in the correct order. (you should definitely make sure that events for each persistenceId are inserted in the correct order)

**Comment by zmarois** [comment]
I am trying out a migration from a Cassandra akka-persistence implementation. I had considered using the highest-level interface the most likely for integration success, which is why I targeted the write journal, but you're right, I'll probably be fine just using the Serializer and doing the insert myself.

I'm explicitly trying not to use a persistent actor because I want to ensure my sequence number (at least per entity) to be the same in both DBs. I can *probably* ensure that by inserting in the same order, but I'd feel more confident about it if I utilized the existing sequence number.

I'd love for global event ordering to be at least similar, but it's not absolutely necessary. For data truncation, I will want a way to identify old data, which I could use sequence number if I insert in the same order.

Thanks for the simpler idea and for being a sounding board.
