### ISSUE TITLE
Duplicate key exceptions on adding event

### ISSUE THREAD

**Issue by josh-s-g** [dnvriend/akka-persistence-jdbc#213]
I'm finding occasional errors like this:
```
Failed to persist event type [com.foo.bar.Event] with sequence number [3] for persistenceId [49156412-a1e7-4ed1-b5bf-25470b0596f7].
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "journal_pkey"
  Detail: Key (persistence_id, sequence_number)=(49156412-a1e7-4ed1-b5bf-25470b0596f7, 3) already exists.
```
If this symptomatic of an incorrect implementation or configuration on my part? I'm effectively doing this:
```
    val persistentActor = system.actorOf(Props(new FooPersistentActor(uuid)))
    persistentActor ? e
```

And in the actor:
```
  val receiveCommand: Receive = {
    case e: Event =>
      persist(e) { event =>
        updateState(e)
   ...
```
Is there a way to check (and then retry) if the `sequence_number` has been updated?

**Comment by ollyw** [comment]
@josh-s-g what was the output of your investigation. I am seeing the same duplicate key errors.

**Comment by renatocaval** [comment]
That error usually happens when you have two instances of the same entity, in the case here `49156412-a1e7-4ed1-b5bf-25470b0596f7`, that are both trying to write an event. 

This is a deployment error. Have you deployed two instances of the same application? 
If so, you need to use akka cluster sharding and shard your persistent actors otherwise you can easily have them load in two JVM and trying to write to the journal.

**Comment by josh-s-g** [comment]
Yes, it was a mistake with the way I was creating Actors (hence 2 trying to write events with the same persistence ID.

**Comment by ollyw** [comment]
In my case, the only situation that there would be two instances running is if the cluster were split-brain, as the actors with the errors are cluster singletons. There is nothing in the logs to indicate split brain (there is an SBR running), and the logs don't indicate that actor logging on more than one node. I will keep digging. Thanks for you responses.

**Comment by tavisca-asingla** [comment]
In my case, I am getting these exceptions only while saving the snapshot. Never got this error while persisting data in journal. We do have split brain resolver in place. And as journal is not giving such errors, it does not looks to be related to cluster being in split brain. My entityIds are unique as expected. Did anyone get the error while saving the snapshot?

**Comment by tavisca-asingla** [comment]
The error of which I commented above is caused due to slick failing on upsert operation. The if not exists check is failing, the reason is not known. Following are the debug logs of slick:
```
Executing prepared update: HikariProxyPreparedStatement@1548472201 wrapping update "event"."snapshot" set "created"=?,"snapshot"=? where "persistence_id"=? and "sequence_number"=?; insert into "event"."snapshot" ("persistence_id","sequence_number","created","snapshot") select ?,?,?,? where not exists (select 1 from "event"."snapshot" where "persistence_id"=? and "sequence_number"=?)
```
dont know why insert is getting triggered, when it is already checking for records existence.
Following is the error:
```
Detail: Key (persistence_id, sequence_number)=(MEMBERSHIP-1208784a-b2bb-44cd-b5c6-9117b0a91968, 5) already exists.
```
