### ISSUE TITLE
Sharding to multiple databases

### ISSUE THREAD

**Issue by esamson** [dnvriend/akka-persistence-jdbc#244]
I'm thinking of using a sharded database architecture like the one described in https://aws.amazon.com/blogs/database/sharding-with-amazon-relational-database-service/

This would allow scaling out to multiple databases, for example, by hash partitioning based on the `persistence_id` so that journal and snapshots are distributed to separate DB hosts.

Is this achievable with a custom *SlickDatabaseProvider* or a custom *DAO*?

**Comment by renatocaval** [comment]
The fact that you are sharding over different databases should be transparent to your app, I think. Ideally, this should be handled by a driver that is smart enough to pick connections from different pools.

You will have to reverse engineer the plugin to understand how it works. I'm not sure this will be possible though. 

In any case, I would look first on the `SlickDatabaseProvider`. 

(I'm closing this issue because it's a question, not a real issue)

**Comment by WellingR** [comment]
I do not think that this is possible in the current version.
However if the `SlickDatabaseProvider` would know receive the persitenceId when called, then it should be possible to return a specific database connection pool. This could work for the write journal and snapshot journal. However for the read jounal queries this may be much harder to do.
Actually since database sequences will probably not be shared, I think it will not be possible to use the eventsByTag query at all.

**Comment by esamson** [comment]
Thanks for your comments. I was hoping a custom extension might do the trick but it seems this would be a deeper change that can't easily be pursued.

Thanks.
