### ISSUE TITLE
A question on eventsByTag behaviour

### ISSUE THREAD

**Issue by vpavkin** [dnvriend/akka-persistence-jdbc#39]
Hello!
Actively using your plugin, thank you for it :)

I have a question regarding persistence-query realtime streams like `eventsByTag`. A system I develop has two separate applications for write-back and read-back and my intent is to make read-back poll the journal and fill the query-side database.
I'm stuck with `eventsByTag` replaying only existing events without supplying events that come later (so it  behaves like `currentEventsByTag`). I inspected the code and it seems that the stream is filled with realtime events only if there's a persistence actor in place. In my case it works on another machine (write-back) and can't feed the read-back stream.

So the question is, am I correct about this behaviour? 
If so, what do you think is the best way to overcome this limitation?

Thank you in advance!

**Comment by dnvriend** [comment]
Hi,

The async-query API has been implemented quite naively. I must rewrite the async-query API so that the query will poll the journal and keep track of its offset. The basic idea behind the current implementation was to overcome the polling behavior of clients, but after consideration, this is not possible.

**Comment by vpavkin** [comment]
I see. Thanks for detailed explanation :)
