### ISSUE TITLE
Deleting journal messages won't work well over time

### ISSUE THREAD

**Issue by manuelbernhardt** [dnvriend/akka-persistence-jdbc#79]
A client's system was getting an increasing amount of timed out circuit breaker exceptions when it came to deleting past messages in one of the actors (once a snapshot had been created), even without any load on the system. It turned out that there were about 600000 soft-deleted messages in the database.

The [query to delete those messages](https://github.com/dnvriend/akka-persistence-jdbc/blob/master/src/main/scala/akka/persistence/jdbc/dao/bytea/journal/JournalQueries.scala#L33) does not filter out messages already marked as deleted, which means that there'll be an update on all messages (which turns out to take some time).

So I think it would make sense to add this filter on the deleted field to avoid this kind of situation.

I haven't seen any way to not use soft deletion - I suppose a custom DAO would be the right answer to that?

Thanks!

**Comment by dnvriend** [comment]
Hi Manuel, love your book :) I will put it on the bug list. I am thinking about a complete rewrite as Slick hasn't brought what I thought it would to the project. Also the design should change to support the akka-persistence-query responsibilities better.

**Comment by manuelbernhardt** [comment]
Thanks! Slick's licensing for oracle databases may also be a little problematic. I know it's a bit of a jungle out there when it comes to finding a good persistence library for Scala. For this case though where there are only two tables I'd think that [anorm](https://www.playframework.com/documentation/2.5.x/ScalaAnorm) might be a good fit, especially since it's got a few improvements recently and is a stand-alone project (i.e. not coupled to Play any longer) and it doesn't add any kind of magic.

**Comment by dnvriend** [comment]
The next release will filter those already deleted, let me know if it works!

**Comment by skisel** [comment]
Hi @dnvriend 

It seems akka-persistence-jdbc still in the current master branch considers "deteled" in the ReadJournalQueries part. Am I missing something or it should filter them out?

**Comment by dnvriend** [comment]
@skisel You are correct, the eventsByPersistenceId should filter out the deleted events which it doesn't.

**Comment by svenwiegand** [comment]
My addition to @manuelbernhardt's message regarding persistence libraries: Totally agree that anorm is an easy to use choice. I've used it in some small sized projects and would choose it again everytime, because it gives full SQL control and provides easy statement building and result parsing. Only drawback in multi database scenarios might be, that you are writing native SQL and so need to target every supported database.

JOOQ is also a nice choice which worked fine for us in a large scala application. You get also full control of your SQL, but JOOQ cares about creating the correct queries for the target database. They provide a nice Scala DSL. Drawback: It's only free to use for opensource databases.

**Comment by WellingR** [comment]
In the current version of [JournalQueries.scala](https://github.com/dnvriend/akka-persistence-jdbc/blob/master/src/main/scala/akka/persistence/jdbc/journal/dao/JournalQueries.scala) the deleted filter is already being used in the `markJournalMessagesAsDeleted ` query.

Clossing this issue, since this bug seems to have been resolved already
