### ISSUE TITLE
Persistence failure

### ISSUE THREAD

**Issue by Elqul** [dnvriend/akka-persistence-jdbc#99]
hello,
i am a newbie to akka and scala programming  :) , anyway, in one of my projects i am getting this error
`Persistence failure when replaying events for persistenceId [Dialog_419352970_1_1969176997]. Last known sequence number [0] 
akka.pattern.CircuitBreakerOpenException: Circuit Breaker is open; calls are failing fast `

what is how can this be fixed ?

**Comment by dnvriend** [comment]
Hi, no problem, glad to receive a new programmer into the reactive community so welcome! The error message isn't much to go on, but what it does tell us is that the circuit breaker is tripping and this could be because of many problems. If you edit or add a logback.xml file to your src/main/resources folder and put the contents of the following [logback.xml](https://github.com/dnvriend/akka-persistence-jdbc/blob/master/src/test/resources/logback.xml) file in it, and of course remove the commented lines from the loggers then you should get more debug logging on the console and maybe find out something more.

**Comment by dnvriend** [comment]
I've created a small test project called [akka-persistence-jdbc-test](https://github.com/dnvriend/akka-persistence-jdbc-test), It works and does eventing and snapshotting, maybe you can take a look and see what the difference are.

**Comment by WellingR** [comment]
Closing this issue, since the reporter has not responded since almost 5 months (feel free to re-open if there still is a problem)
